# Configuracion general
server:
  port: 8082

spring:
  application:
    name: "redis-person"

  # Datasources
  datasource:
    url: jdbc:mariadb://localhost:3308/person
    username: spring
    password: spring
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: 'none'